name: flutter_eval
description: Interpreter for Flutter, using dart_eval
version: 0.3.0
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_eval: any

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
    
flutter:
