name: flutter_eval
description: Interpreter for Flutter, using dart_eval
version: 0.4.0
homepage: https://github.com/ethanblake4/dart_eval

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_eval: ^0.4.0
  path_provider: ^2.0.11
  http: ^0.13.5

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
    
flutter:
